language: android
jdk: oraclejdk8
dist: trusty

env:
  global:

android:
  components:
   # Additional components	
    - extra-google-google_play_services	
    - extra-google-m2repository	
    - extra-android-m2repository	
    - extra-android-support

  licenses:

before_install:

before_script:
  - chmod +x gradlew

#script:
#  - ./gradlew clean build
#  - ./gradlew test
